SVOBODEN_STICKER = "CAACAgIAAxkBAAEMJ2JmS6ZeaqIypNnGu87SIgZci2gb8QAC5UYAAoZACEoJRP5JxfZ4FDUE"
T34_STICKERS = [
    "CAACAgIAAxkBAAP2ZpRQsBhRjNj0WIhDgRJQ_TJUEUUAAitSAAIdsphIaq4AAYD1stiINQQ",
    "CAACAgIAAxkBAAP8ZpRQ2FPEb7YL4UezY5yTM7XDtTsAAvRRAALJjZlIHIolGlenIlY1BA",
    "CAACAgIAAxkBAAIBAAFmlFDnoiBXxqovS2Y0EBknYLotmwAC3kwAApfokUgkdm-FgbaECjUE",
]
